import React, { useState } from 'react';
import { X, User, Phone, Mail, Calendar, Clock, Star, TrendingUp, DollarSign, Briefcase } from 'lucide-react';
import { formatDate, formatCurrency } from '../../../../lib/utils';
import { StaffMember } from '../../../../hooks/useStaff';
import { useFinance } from '../../../../hooks/useFinance';
import { useAppointments } from '../../../../hooks/useAppointments';

interface StaffProfileContentProps {
    staff: StaffMember;
    onClose: () => void;
    clinicId?: string;
}

export const StaffProfileContent: React.FC<StaffProfileContentProps> = ({ staff, onClose, clinicId }) => {
    const [activeTab, setActiveTab] = useState<'overview' | 'financial' | 'cases'>('overview');
    const { transactions, loading: loadingFinance } = useFinance(clinicId, undefined, staff.id);
    const { appointments, loading: loadingAppointments } = useAppointments(clinicId);

    // Filter appointments for this doctor
    const assignedCases = appointments.filter(a => a.doctorId === staff.id);

    // Calculate Financial Stats
    const salaries = transactions.filter(t => t.category === 'salary');
    const commissions = transactions.filter(t => t.category === 'commission' || (t.type === 'income' && t.doctorId === staff.id));
    // Commissions might be INCOME generated by doctor, or EXPENSE paid as commission?
    // Usually "Commissions this month" implies what they EARNED. 
    // If it's income generated: t.type === 'income' && t.doctorId === staff.id
    // If it's commission PAID to them: t.type === 'expense' && t.category === 'commission'

    // For now, let's treat "Generated Income" as a stat, and "Paid Salary" as Expense.
    const incomeGenerated = transactions.filter(t => t.type === 'income' && t.doctorId === staff.id).reduce((sum, t) => sum + t.amount, 0);
    const totalSalariesPaid = salaries.reduce((sum, t) => sum + t.amount, 0);


    const renderOverview = () => (
        <div className="space-y-6 animate-in slide-in-from-bottom-4 duration-500">
            {/* Personal Info */}
            <div className="bg-gray-50 rounded-xl p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">المعلومات الشخصية</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div><label className="block text-sm font-medium text-gray-700">الاسم الكامل</label><p className="text-gray-900">{staff.name}</p></div>
                    <div><label className="block text-sm font-medium text-gray-700">الهاتف</label><p className="text-gray-900">{staff.phone}</p></div>
                    <div><label className="block text-sm font-medium text-gray-700">البريد الإلكتروني</label><p className="text-gray-900">{staff.email}</p></div>
                    <div><label className="block text-sm font-medium text-gray-700">القسم</label><p className="text-gray-900">{staff.department}</p></div>
                </div>
            </div>

            {/* Work Info */}
            <div className="bg-gray-50 rounded-xl p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">معلومات العمل</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div><label className="block text-sm font-medium text-gray-700">المنصب</label><p className="text-gray-900">{staff.position}</p></div>
                    <div><label className="block text-sm font-medium text-gray-700">تاريخ التوظيف</label><p className="text-gray-900">{formatDate(staff.hireDate)}</p></div>
                    <div><label className="block text-sm font-medium text-gray-700">ساعات العمل</label><p className="text-gray-900">{staff.workSchedule.startTime} - {staff.workSchedule.endTime}</p></div>
                    <div><label className="block text-sm font-medium text-gray-700">الراتب الأساسي</label><p className="text-gray-900 font-bold">{(staff.salary || 0).toLocaleString()} د.ع</p></div>
                </div>
            </div>

            {/* Skills */}
            <div className="bg-gray-50 rounded-xl p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-4">المهارات</h3>
                <div className="flex flex-wrap gap-2">
                    {staff.skills.map((skill, index) => (
                        <span key={index} className="px-3 py-1 bg-blue-100 text-blue-800 rounded-full text-sm font-medium">{skill}</span>
                    ))}
                </div>
            </div>
        </div>
    );

    const renderFinancials = () => (
        <div className="space-y-6 animate-in slide-in-from-bottom-4 duration-500">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="bg-green-50 p-4 rounded-xl border border-green-100">
                    <h4 className="text-green-800 font-bold mb-1">الراتب الأساسي</h4>
                    <p className="text-2xl font-bold text-green-600">{(staff.salary || 0).toLocaleString()} <span className="text-sm font-normal text-gray-500">د.ع</span></p>
                </div>
                <div className="bg-blue-50 p-4 rounded-xl border border-blue-100">
                    <h4 className="text-blue-800 font-bold mb-1">إيرادات حققها</h4>
                    <p className="text-2xl font-bold text-blue-600">
                        {incomeGenerated.toLocaleString()} <span className="text-sm font-normal text-gray-500">د.ع</span>
                    </p>
                </div>
                <div className="bg-red-50 p-4 rounded-xl border border-red-100">
                    <h4 className="text-red-800 font-bold mb-1">مجموع الرواتب المستلمة</h4>
                    <p className="text-2xl font-bold text-red-600">
                        {totalSalariesPaid.toLocaleString()} <span className="text-sm font-normal text-gray-500">د.ع</span>
                    </p>
                </div>
            </div>

            <div className="bg-white border rounded-xl overflow-hidden shadow-sm">
                <div className="p-4 border-b bg-gray-50">
                    <h3 className="font-bold text-gray-700">سجل المعاملات المالية</h3>
                </div>
                {loadingFinance ? (
                    <div className="p-8 text-center">جاري التحميل...</div>
                ) : (
                    <table className="w-full text-right">
                        <thead className="bg-gray-50">
                            <tr>
                                <th className="p-4 font-semibold text-gray-600">التاريخ</th>
                                <th className="p-4 font-semibold text-gray-600">النوع</th>
                                <th className="p-4 font-semibold text-gray-600">التصنيف</th>
                                <th className="p-4 font-semibold text-gray-600">المبلغ</th>
                                <th className="p-4 font-semibold text-gray-600">الملاحظات</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y">
                            {transactions.map(record => (
                                <tr key={record.id} className="hover:bg-gray-50">
                                    <td className="p-4">{formatDate(record.date)}</td>
                                    <td className="p-4">
                                        <span className={`px-2 py-1 rounded text-xs font-bold ${record.type === 'income' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                                            }`}>
                                            {record.type === 'income' ? 'إيراد' : 'مصروف'}
                                        </span>
                                    </td>
                                    <td className="p-4">
                                        <span className="px-2 py-1 rounded-full bg-gray-100 text-xs">
                                            {record.category === 'salary' ? 'راتب' :
                                                record.category === 'treatment' ? 'جلسة علاج' :
                                                    record.category}
                                        </span>
                                    </td>
                                    <td className="p-4 font-bold">{formatCurrency(record.amount)}</td>
                                    <td className="p-4 text-gray-500 text-sm max-w-xs truncate">{record.description}</td>
                                </tr>
                            ))}
                            {transactions.length === 0 && (
                                <tr><td colSpan={5} className="p-8 text-center text-gray-500">لا توجد سجلات مالية</td></tr>
                            )}
                        </tbody>
                    </table>
                )}
            </div>
        </div>
    );

    const renderCases = () => (
        <div className="space-y-6 animate-in slide-in-from-bottom-4 duration-500">
            <div className="bg-white border rounded-xl overflow-hidden shadow-sm">
                <div className="p-4 border-b bg-gray-50 flex justify-between items-center">
                    <h3 className="font-bold">الحالات المعالجة ({assignedCases.length})</h3>
                </div>
                {loadingAppointments ? (
                    <div className="p-8 text-center">جاري التحميل...</div>
                ) : (
                    <table className="w-full text-right">
                        <thead className="bg-white">
                            <tr>
                                <th className="p-4 font-semibold text-gray-600">المريض</th>
                                <th className="p-4 font-semibold text-gray-600">نوع العلاج</th>
                                <th className="p-4 font-semibold text-gray-600">التاريخ</th>
                                <th className="p-4 font-semibold text-gray-600">الحالة</th>
                                <th className="p-4 font-semibold text-gray-600">الإيراد</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y">
                            {assignedCases.map((c, i) => (
                                <tr key={i} className="hover:bg-gray-50">
                                    <td className="p-4 font-medium">{c.patientName}</td>
                                    <td className="p-4">
                                        {c.type === 'consultation' ? 'كشفية' :
                                            'علاج' // We don't have detailed treatment type in appointment list unless we fetch it or store it.
                                        }
                                    </td>
                                    <td className="p-4 text-gray-500">{formatDate(c.date)}</td>
                                    <td className="p-4">
                                        <span className={`px-2 py-1 rounded text-xs font-bold ${c.status === 'completed' ? 'bg-green-100 text-green-700' : 'bg-blue-100 text-blue-700'
                                            }`}>
                                            {c.status === 'completed' ? 'مكتمل' :
                                                (c.status as string) === 'scheduled' ? 'مجدول' :
                                                    c.status === 'cancelled' ? 'ملغي' : c.status}
                                        </span>
                                    </td>
                                    <td className="p-4 font-bold">{(c.cost || 0).toLocaleString()}</td>
                                </tr>
                            ))}
                            {assignedCases.length === 0 && (
                                <tr><td colSpan={5} className="p-8 text-center text-gray-500">لا توجد حالات مسجلة لهذا الطبيب</td></tr>
                            )}
                        </tbody>
                    </table>
                )}
            </div>
        </div>
    );

    return (
        <>
            <div className="sticky top-0 bg-white border-b border-gray-200 z-10">
                <div className="p-6 flex items-center justify-between pb-0">
                    <div>
                        <h2 className="text-2xl font-bold text-gray-900">{staff.name}</h2>
                        <p className="text-gray-500 mb-4">{staff.position} - {staff.department}</p>
                    </div>
                    <button onClick={onClose} className="p-2 hover:bg-gray-100 rounded-lg mb-4"><X className="w-6 h-6 text-gray-500" /></button>
                </div>

                {/* Tabs */}
                <div className="flex px-6 space-x-reverse space-x-6">
                    {[
                        { id: 'overview', label: 'نظرة عامة', icon: User },
                        { id: 'financial', label: 'المالية', icon: DollarSign },
                        { id: 'cases', label: 'الحالات', icon: Briefcase },
                    ].map(tab => (
                        <button
                            key={tab.id}
                            onClick={() => setActiveTab(tab.id as any)}
                            className={`flex items-center gap-2 pb-4 px-2 border-b-2 transition-colors ${activeTab === tab.id
                                ? 'border-blue-600 text-blue-600 font-bold'
                                : 'border-transparent text-gray-500 hover:text-gray-700'
                                }`}
                        >
                            <tab.icon className="w-5 h-5" />
                            {tab.label}
                        </button>
                    ))}
                </div>
            </div>

            <div className="p-6">
                {activeTab === 'overview' && renderOverview()}
                {activeTab === 'financial' && renderFinancials()}
                {activeTab === 'cases' && renderCases()}
            </div>
        </>
    );
};
